
###

POST http://lb-b9c8bb43.elb.localhost.localstack.cloud:4566/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "consumesr test_after for token ",
  "email": "kafkandew@example.com",
  "address": "Whitse town",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}


###