
###

POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: {{token}}

{
  "name": "consumer test_after for token ",
  "email": "kafkanew@example.com",
  "address": "White town",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}


###